- hosts: localhost
  become: yes

  pre_tasks:

    - name: Update && Dist-Upgrade the OS via apt
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 # 1 day

  roles:
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - platformio.platformio-ide
          - cweijan.vscode-office
          - robole.marky-stats
          - yzhang.markdown-all-in-one
          - ms-vsliveshare.vsliveshare-pack
          - mhutchie.git-graph
    - role: staticdev.signal
    - role: manala.zsh
    - role: manala.ohmyzsh

  tasks:

    ## CAD/CAM Programs ##

    - name: Install Prusa Slicer from default apt repositorys
      apt:
        name: prusa-slicer

    - name: Install FreeCAD from default apt repositorys
      apt:
        name: freecad

    - name: Install Blender from default apt repositorys
      apt:
        name: blender

    - name: Install OpenSCAD from default apt repositorys
      apt:
        name: openscad

    - name: Install GIMP from default apt repositorys
      apt:
        name: gimp

    - name: Install Inkscape from default apt repositorys
      apt:
        name: inkscape

    - name: Install KiCad from default apt repositorys
      apt:
        name: kicad

    - name: Install Printrun from default apt repositorys
      apt:
        name: printrun

    - name: Install Scribus from default apt repositorys
      apt:
        name: scribus

    - name: Install OpenShot from default apt repositorys
      apt:
        name: openshot

    - name: Install Darktable from default apt repositorys
      apt:
        name: darktable


    ## Backup Programs ##

    - name: Install Syncthing from default apt repositorys
      apt:
        name: syncthing

    - name: Install KeePassXC from default apt repositorys
      apt:
        name: keepassxc

    - name: Install Nextcloud Desktop from default apt repositorys
      apt:
        name: nextcloud-desktop


    ## Writing Programs ##

    - name: Install Pandoc from default apt repositorys
      apt:
        name:
          - pandoc
          - pandoc-citeproc

    - name: Install TeX Live from default apt repositorys
      apt:
        name:
          - texlive
          - texlive-lang-german
          - texlive-latex-extra
          - texlive-fonts-extra
          - texlive-luatex

    - name: Install Calibre from default apt repositorys
      apt:
        name: calibre


    ## Coding Programs ##

    - name: Install Vagrant from default apt repositorys
      apt:
        name:
          - vagrant
          - virtualbox

    - name: Install Arduino IDE from default apt repositorys
      apt:
        name: arduino

    - name: Install Android Tools from default apt repositorys
      apt:
        name:
          - adb
          - fastboot


    ## Media Programs ##

    - name: Install VLC media player from default apt repositorys
      apt:
        name: vlc

    - name: Install Audacity from default apt repositorys
      apt:
        name: audacity

    - name: Install Ardour from default apt repositorys
      apt:
        name: ardour

    - name: Install OBS Studio from default apt repositorys
      apt:
        name: obs-studio


    ## Gaming Programs ##

    - name: Install Steam from default apt repositorys
      apt:
        name: steam


    ## Communications Programs ##

    - name: Install Telegram Desktop from default apt repositorys
      apt:
        name: telegram-desktop

    - name: Install Slack Desktop from default apt repositorys
      apt:
        name: slack-desktop

    - name: Install Discord from default apt repositorys
      apt:
        name: discord


    ## Learning Programs ##

    - name: Install Anki from default apt repositorys
      apt:
        name: anki


    ## Finance Programs ##

    - name: Install GnuCash from default apt repositorys
      apt:
        name: gnucash


    ## Web Programs ##

    - name: Install Chromium from default apt repositorys
      apt:
        name: chromium-browser

    - name: Install Transmission from default apt repositorys
      apt:
        name: transmission

    - name: Install TIPP10 from default apt repositorys
      apt:
        name: tipp10


# git config --global user.email "you@example.com"
# git config --global user.name "Your Name"
# common
# user
# deepnest
# etcher
# lightburn
# veracrypt
# element
# zotero
# typora
# xournal++
# teams
# zoom
# cisco
# parsec
# among us
# minecraft
# table top simulator

# acpi
# asciidoc
# thunderbird
# git-lfs
# grsync
# inkstitch
# linphone / sip client
# ncdu
# nmap
# node
# npm
# octave
# implicitcad
# qemu
# remmina
# subversion
# git-svn
# supertuxkart
# sweethome3d
# teamviewer
# tlp
# tree
# playonlinux
# bitwarden
# vim
# unattended-upgraded / apt-listchanges
# cheese
# davinci resolve
# lutris
# pdfgrep
# powertop
# traceroute
